name: Rebrand Code

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write   # 👈 allow pushing commits back

jobs:
  rebrand:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # 👈 authenticate checkout with write access

      - name: Apply rebrand patch
        run: |
          git apply rebrand_patch.diff || echo "Patch already applied, continuing..."

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Applied rebrand patch" || echo "No changes to commit"
          git push
